version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./USWMusicals.WebClient/dist:/usr/share/nginx/html:ro
    depends_on:
      - showservice
      - bookingservice
    networks:
      - app-network

  showservice:
    build:
      context: ./USWMusicals.ShowService
      dockerfile: Dockerfile
    expose:
      - "80"
    networks:
      - app-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  bookingservice:
    build:
      context: ./USWMusicals.BookingService
      dockerfile: Dockerfile
    expose:
      - "80"
    networks:
      - app-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  app-network:
    driver: bridge
