version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./USWMusicals.WebClient/dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - showservice
      - bookingservice

  showservice:
    build:
      context: ./USWMusicals.ShowService
      dockerfile: Dockerfile
    expose:
      - "80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80

  bookingservice:
    build:
      context: ./USWMusicals.BookingService
      dockerfile: Dockerfile
    expose:
      - "80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
