# Docker Compose configuration for USW Musicals

services:
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - "80:80"
    depends_on:
      showservice:
        condition: service_healthy
      bookingservice:
        condition: service_healthy
    networks:
      - app-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80

  showservice:
    build:
      context: ./USWMusicals.ShowService
      dockerfile: Dockerfile
    expose:
      - "80"
    networks:
      - app-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/health || exit 1"]
      interval: 60s
      timeout: 30s
      retries: 5
      start_period: 120s

  bookingservice:
    build:
      context: ./USWMusicals.BookingService
      dockerfile: Dockerfile
    expose:
      - "80"
    networks:
      - app-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/health || exit 1"]
      interval: 60s
      timeout: 30s
      retries: 5
      start_period: 120s

networks:
  app-network:
    driver: bridge
